Add support to nucleo h563zi
platformio/platform-ststm32 pull request #800
Opened 2024-09-21 02:30 UTC by patrickelectric

Fix #730

2024-09-21 03:09 UTC, patrickelectric commented
ping @valeros

2024-09-23 10:36 UTC, valeros requested changes

2024-09-23 10:36 UTC, valeros commented on boards/nucleo_h563zi.json
> +    "jlink_device": "STM32H723IE",
Probably a typo, should be `STM32H563ZI`.

2024-09-23 10:36 UTC, valeros commented on boards/nucleo_h563zi.json
> +    "zephyr"
`stm32cube`, `mbed` and `libopencm3` are not available for this board.

2024-09-23 10:36 UTC, valeros commented on boards/nucleo_h563zi.json
> +}
Add EOL please.

2024-09-23 10:37 UTC, valeros commented
Hi @patrickelectric, please review my comments above.

2024-09-23 13:58 UTC, valeros commented on boards/nucleo_h563zi.json
> +    "openocd_target": "stm32h7x",
The current OpenOCD package doesn't support the `stm32h5` family, so it should be removed completely.

2024-09-24 00:45 UTC, patrickelectric commented
@valeros check now, everything should be fixed

2024-09-24 11:19 UTC, valeros commented
> check now, everything should be fixed

Thanks, have you tested this board with PlatformIO? Does it work as expected?

2024-09-24 19:27 UTC, patrickelectric commented
> > check now, everything should be fixed
> 
> Thanks, have you tested this board with PlatformIO? Does it work as expected?

I did it using openocd, I know that the platformio openocd package does not support it but I'm using the OpenOCD of STM.

2024-09-25 10:10 UTC, valeros commented
> I did it using openocd, I know that the platformio openocd package does not support it but I'm using the OpenOCD of STM.

I see. Honestly, I’m a bit hesitant to add a new board that we can’t program or debug with our current tools. The latest stable OpenOCD doesn’t support the H5 family, and we don’t use any OpenOCD forks. So, basically, you’ll have to drop `st-link` and `cmsis-dap` from the list of upload protocols. That means the board will need to be programmed either through mass storage (which I think the latest ST-Links support) or using an external J-Link debug probe, but that’s going to make the developer experience pretty rough.

2024-10-02 17:46 UTC, ypearson-bdai commented
its not so bad, just care about building the binary, There are other options to flash other than openocd

2024-10-02 18:22 UTC, patrickelectric commented
> its not so bad, just care about building the binary, There are other options to flash other than openocd

Yeah, the binary is working fine.

2024-10-02 22:02 UTC, ypearson-bdai commented
> > its not so bad, just care about building the binary, There are other options to flash other than openocd
> 
> Yeah, the binary is working fine.

Yeah this seems to working okay. Not sure why this isn't being merged.

2024-12-11 08:39 UTC, patrickelectric commented
@valeros I think that is fine as it is, once the tools update the support will be already there. Otherwise, we can just let people waiting.. and that's not good. I prefer to have an option than nothing at all.

2025-02-02 15:35 UTC, lm324bruno commented
Hy folks, any update on when we may expect that change request approved? Waiting for that board support ...

2025-02-02 15:44 UTC, patrickelectric commented
Ping @valeros

2025-02-04 13:06 UTC, valeros commented
Hi @patrickelectric, if you insist on merging, then please remove unsupported tools from the `debug` and `upload` sections, so only `mbed` and `jlink` methods are left (`mbed` should be the default choice).

2025-02-17 11:43 UTC, lm324bruno commented
any update? Sorry for bothering, but it seems platformio currently do not support any new nucleo144 boards, wondering if there's a chance to get at least one new board in ...

2025-02-17 11:56 UTC, patrickelectric commented
@valeros debug and upload section removed.

2025-02-17 12:00 UTC, valeros commented
@patrickelectric you shouldn't have removed the entire sections, only unsupported tools.

2025-02-17 12:21 UTC, patrickelectric commented
@valeros let me know if it's correct now.

2025-02-17 13:27 UTC, merged

2025-02-17 13:27 UTC, valeros commented
Thanks, merged.